examenParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestiontienda/',include('gestiontienda.urls'))
]

gestiontienda/urls.py
from django.urls import path
from  . import views

app_name='gestiontienda'

urlpatterns=[
    path('',views.index,name='index'),
    path('tiendas',views.registroTienda,name='registroTienda'),
    path('productos',views.registroProducto,name='registroProducto'),
    path('eliminarProducto/<str:idProducto>', views.eliminarProducto,name='eliminarProducto'),
    path('eliminarProductoTienda/<str:idProducto>', views.eliminarProductoTienda,name='eliminarProductoTienda'),
    path('eliminarTienda/<str:idTienda>', views.eliminarTienda,name='eliminarTienda'),
    path('asignarProducto',views.asignarProducto,name='asignarProducto'),
    path('verProductos/<str:idTienda>',views.verProductos,name='verProductos')
    
]

gestiontienda/models.py
from django.db import models

# Create your models here.

class tienda(models.Model):
    direccion=models.CharField(max_length=64, blank=True, null=True)
    provincia=models.CharField(max_length=32, blank=True, null=True)
    region=models.CharField(max_length=32, blank=True, null=True)
    fechaCreacion=models.CharField(max_length=32, blank=True, null=True)
    telefonoContacto=models.CharField(max_length=32, blank=True, null=True)



class producto(models.Model):
    descripcion=models.CharField(max_length=64, blank=True, null=True)
    codigo=models.CharField(max_length=32, blank=True, null=True)
    precioVenta=models.CharField(max_length=32, blank=True, null=True)
    cantidad=models.CharField(max_length=32, blank=True, null=True)
    tiendaProducto = models.ForeignKey(tienda,on_delete=models.SET_NULL,blank=True, null=True)
    #productoTienda = models.OneToOneField(tienda, on_delete=models.SET_NULL, blank=True, null=True)

gestiontienda/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import tienda ,producto

# Create your views here.
listaUsuario = []

def index(request):
     return render(request,'inicio.html')


def registroTienda(request):
    if request.method=='POST':
        tiendaDireccion= request.POST.get('tiendaDireccion')
        tiendaProvincia= request.POST.get('tiendaProvincia')
        tiendaRegion= request.POST.get('tiendaRegion')
        tiendaFechaCreacion= request.POST.get('tiendaFechaCreacion')
        tiendaTelefonoContacto= request.POST.get('tiendaTelefonoContacto')
        tienda.objects.create(
            direccion=tiendaDireccion,
            provincia=tiendaProvincia,
            region=tiendaRegion,
            fechaCreacion=tiendaFechaCreacion,
            telefonoContacto=tiendaTelefonoContacto
        )
        #listaUsuario.append([nombreUsuario,apellidoUsuario])
        return HttpResponseRedirect(reverse('gestiontienda:registroTienda'))
    return render(request,'registroTienda.html',{
        'tiendaTotales':tienda.objects.all().order_by('id'),
         'productoTotales':producto.objects.all().order_by('id'),
    })


def registroProducto(request):
    if request.method=='POST':
        descripcion=request.POST.get('descripcionProducto')
        codigo=request.POST.get('codigoProducto')
        precioVenta=request.POST.get('precioventaProducto')
        cantidad=request.POST.get('cantidadProducto')
        producto.objects.create(
            descripcion=descripcion,
            codigo=codigo,
            precioVenta=precioVenta,
            cantidad=cantidad
        )
        return HttpResponseRedirect(reverse('gestiontienda:registroProducto'))
    return render(request,'registroProducto.html',{
        'productoTotales':producto.objects.all().order_by('id'),
        'tiendaTotales':tienda.objects.all().order_by('id')        
    })


def asignarProducto(request):
    if request.method == 'POST':
        idTienda= request.POST.get('tiendaSeleccionada')
        idProducto= request.POST.get('productoSeleccionado')
        objetoProducto=producto.objects.get(id=idProducto)
        objetoTienda=tienda.objects.get(id=idTienda)
        objetoProducto.tiendaProducto=objetoTienda
        objetoProducto.save()
        return HttpResponseRedirect(reverse('gestiontienda:registroTienda'))

def eliminarProducto(request,idProducto):
    productoEliminar= producto.objects.get(id=idProducto)
    productoEliminar.delete()
    return HttpResponseRedirect(reverse('gestiontienda:registroProducto'))

def eliminarProductoTienda(request,idProducto):
    productoEliminar= producto.objects.get(id=idProducto)
    productoEliminar.delete()
    return HttpResponseRedirect(reverse('gestiontienda:registroTienda'))

def eliminarTienda(request,idTienda):
    tiendaEliminar= tienda.objects.get(id=idTienda)
    tiendaEliminar.delete()
    return HttpResponseRedirect(reverse('gestiontienda:registroTienda'))


def  verProductos(request,idTienda):
    tiendaSeleccionada=tienda.objects.get(id=idTienda)   
    return render(request,'detalleTienda.html',{
      'infoproductosTiendas':tiendaSeleccionada.producto_set.all().order_by('id'),
      'tiendaSeleccionada':tiendaSeleccionada
      
    })
    

        

gestiontienda/templates/detalleTienda.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Detalle Tienda</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'index.css' %}">
    </head>
    <body>
        <div class="bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-10 text-white">
                        <div class="row">
                            <div class="col-8">
                                <h5>Direccion Tienda : {{ tiendaSeleccionada.direccion }}</h5>
                            </div>
                            <div class="col-2">
                                <a class="btn btn-warning btn-sm" href="{% url 'gestiontienda:registroTienda' %}"><i class="fa-solid fa-undo">Regresar</i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered" >
                        <thead class="table-dark" >
                            <th>Descripcion</th>
                            <th>Codigo</th>
                            <th>Precio venta</th>
                            <th>cantidad</th>
                            <th text-align="center">Eliminar producto</th>                                                 
                        </thead>
                        <tbody>
                            {% for infoproducto  in infoproductosTiendas %}
                            <tr>
                                <td>{{infoproducto.descripcion}}</td>
                                <td>{{infoproducto.codigo}}</td>
                                <td>{{infoproducto.precioVenta}}</td>
                                <td>{{infoproducto.cantidad}}</td>    
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'gestiontienda:eliminarProductoTienda' infoproducto.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

gestiontienda/templates/inicio.html
<!DOCTYPE html>
<html>
    <head>
        <title>LogoBackery</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-10 text-white">
                        <div class="row">
                            <div class="col-8">
                                <h5>Bienvenido : Modulo administracion</h5>
                            </div>
                            <div class="col-2">
                                <a href="{% url 'gestiontienda:registroTienda' %}"><i class="fa-solid fa-store"></i>TIENDAS</a>                                
                            </div>
                            <div class="col-2">     
                                                       
                            <a href="{% url 'gestiontienda:registroProducto' %}" ><i class="fa-solid fa-cart-shopping"></i></i>PRODUCTOS</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 container">
          
        </div>
        
    </body>
</html>

gestiontienda/templates/registroProducto.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Registro producto</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'index.css' %}">
    </head>
    <body>
        <div class="bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-10 text-white">
                        <div class="row">
                            <div class="col-8">
                                <h5>Bienvenido al modulo de Productos</h5>
                            </div>
                            <div class="col-2">
                                <a href="{% url 'gestiontienda:registroTienda' %}"><i class="fa-solid fa-store"></i>TIENDAS</a>                                
                            </div>
                            <div class="col-2">     
                                                       
                            <a href="{% url 'gestiontienda:registroProducto' %}" ><i class="fa-solid fa-cart-shopping"></i></i>PRODUCTOS</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 text-center">
            <h1>Gestion de productos</h1>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoProducto">Crear producto<i class="fa-solid fa-plus"></i></button>
                </div>
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#asignarProducto">Asignar tienda<i class="fa-solid fa-file-download"></i></button>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered" >
                        <thead class="table-dark" >
                            <th>Descripcion</th>
                            <th>Codigo</th>
                            <th>Precio venta</th>
                            <th>cantidad</th>                            
                            <th text-align="center">Eliminar producto</th>                            
                        </thead>
                        <tbody>
                            {% for producto  in productoTotales %}
                            <tr>
                                <td>{{producto.descripcion}}</td>
                                <td>{{producto.codigo}}</td>
                                <td>{{producto.precioVenta}}</td>
                                <td>{{producto.cantidad}}</td>                                                    
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'gestiontienda:eliminarProducto' producto.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>



<div class="modal fade" tabindex="-1" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'gestiontienda:registroProducto' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Crear producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div>
                            <label>Descripcion :</label>
                            <input class="form-control" type="text" name="descripcionProducto" required>
                        </div>
                        <div>
                            <label>Codigo :</label>
                            <input class="form-control" type="text" name="codigoProducto" required>
                        </div>
                        <div>
                            <label>Precio de venta :</label>
                            <input class="form-control" type="text" name="precioventaProducto" required>
                        </div>
                        <div>
                            <label>Cantidad :</label>
                            <input class="form-control" type="text" name="cantidadProducto" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Crear producto</button>
                </div>
            </form>
        </div>
    </div>
</div>




<div class="modal fade" tabindex="-1" id="asignarProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'gestiontienda:registroProducto' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Asignar Producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div class="col-5">
                            <label>Seleccionar tienda :</label>
                            <select class="form-select" name="tiendaSeleccionada" required>
                                <option value="" selected></option>
                                {% for  tienda  in tiendaTotales%}
                                <option value="{{tienda.id}}">{{tienda.direccion}}</option>
                                {%endfor%}
                            </select>                            
                        </div>
                        <div class="col-5">
                            <label>Seleccionar producto :</label>
                            <select class="form-select" name="productoSeleccionado" required>
                                <option value="" selected></option>
                                {% for  producto  in productoTotales%}
                                <option value="{{producto.id}}">{{producto.descripcion}}</option>
                                {%endfor%}
                            </select>                                
                        </div>                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Asignar producto</button>
                </div>
            </form>
        </div>
    </div>
</div>

gestiontienda/templates/registroTienda.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Registro Tienda</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'index.css' %}">
    </head>
    <body>
        <div class="bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-10 text-white">
                        <div class="row">
                            <div class="col-8">
                                <h5>Bienvenido al modulo de tienda </h5>
                            </div>
                            <div class="col-2">
                                <a href="{% url 'gestiontienda:registroTienda' %}"><i class="fa-solid fa-store"></i>TIENDAS</a>                                
                            </div>
                            <div class="col-2">     
                                                       
                            <a href="{% url 'gestiontienda:registroProducto' %}" ><i class="fa-solid fa-cart-shopping"></i></i>PRODUCTOS</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 text-center">
            <h1>Gestion de tiendas</h1>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevaTienda">Crear Tienda<i class="fa-solid fa-plus"></i></button>
                </div>
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#asignarProducto">Asignar Producto<i class="fa-solid fa-file-download"></i></button>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered" >
                        <thead class="table-dark" >
                            <th>Direccion:</th>
                            <th>Provincia:</th>
                            <th>Region:</th>
                            <th>Fecha Creacion :</th>
                            <th>Telefono contacto :</th>
                            <th>Ver productos</th>  
                            <th text-align="center">Eliminar Tienda</th>                            
                        </thead>
                        <tbody>
                            {% for tienda  in tiendaTotales %}
                            <tr>
                                <td>{{tienda.direccion}}</td>
                                <td>{{tienda.provincia}}</td>
                                <td>{{tienda.region}}</td>
                                <td>{{tienda.fechaCreacion}}</td>    
                                <td>{{tienda.telefonoContacto}}</td>  
                                <td><a class="btn btn-info" href="{% url 'gestiontienda:verProductos' tienda.id %}"><i class="fa-solid fa-eye"></a></td>                        
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'gestiontienda:eliminarTienda' tienda.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>



<div class="modal fade" tabindex="-1" id="nuevaTienda" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'gestiontienda:registroTienda' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Crear tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                        <div class="row form-group justify-content-center mb-4">
                            <div>
                                <label>Direccion :</label>
                                <input class="form-control" type="text" name="tiendaDireccion" required>
                            </div>
                            <br>
                            <div>
                                <label>Provincia :</label>
                                <input class="form-control" type="text" name="tiendaProvincia" required>
                            </div>                        
                            <div>
                                <label>Region :</label>
                                <input class="form-control" type="text" name="tiendaRegion" required>
                            </div>
                            <div>
                                <label>Fecha de Creacion :</label>
                                <input class="form-control" type="date" name="tiendaFechaCreacion" required>
                            </div>
                            <div>
                                <label>Telf.Contacto :</label>
                                <input class="form-control" type="text" name="tiendaTelefonoContacto" required>
                            </div>
                        </div>                   
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Crear Tienda</button>
                </div>
            </form>
        </div>
    </div>
</div>




<div class="modal fade" tabindex="-1" id="asignarProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'gestiontienda:asignarProducto' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Asignar Producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div class="col-5">
                            <label>Seleccionar tienda :</label>
                            <select class="form-select" name="tiendaSeleccionada" required>
                                <option value="" selected></option>
                                {% for  tienda  in tiendaTotales%}
                                <option value="{{tienda.id}}">{{tienda.direccion}}</option>
                                {%endfor%}
                            </select>                            
                        </div>
                        <div class="col-5">
                            <label>Seleccionar producto :</label>
                            <select class="form-select" name="productoSeleccionado" required>
                                <option value="" selected></option>
                                {% for  producto  in productoTotales%}
                                <option value="{{producto.id}}">{{producto.descripcion}}</option>
                                {%endfor%}
                            </select>                                
                        </div>                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Asignar producto</button>
                </div>
            </form>
        </div>
    </div>
</div>

gestiontienda/templates/registroTiendaTmp.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Primer template de Django</title>
        <link rel="stylesheet" href="{% static '/index.css' %}">
    </head>
    <body>
        <h1>Mi primer proyecto en django</h1>
        <form method="post" action="{% url 'gestiontienda:registroTienda' %}">
            {% csrf_token %}
            <div>
                <label>Ingrese su direccion</label>
                <input type="text" name="tiendaDireccion">
            </div>
            <div>
                <label id="nombreInfo">Ingrese su provincia</label>
                <input type="text" name="tiendaProvincia">
            </div>
            <div>
                <label id="nombreInfo">Ingrese su region</label>
                <input type="text" name="tiendaRegion">
            </div>
            <div>
                <label id="nombreInfo">Ingrese su fecha de creacion</label>
                <input type="date" name="tiendaFechaCreacion">
            </div>
            <div>
                <label id="nombreInfo">Ingrese su Telefono</label>
                <input type="text" name="tiendaTelefonoContacto">
            </div>
            <div>
                <button type="submit">Registrar</button>
            </div>
        </form>
        <div>
            <h2>Usuarios de la aplicacion</h2>
            {% for tiendas in listaUsuarios %}
            <div>
                <h5>Direccion : {{ tiendas.direccion }}</h5>
                <h5>Provincia : {{ tiendas.provincia }}</h5>                
                <h5>Region : {{ tiendas.region }}</h5>
                <h5>FechaCreacion : {{ tiendas.fechaCreacion }}</h5>
                <h5>Telefono de contacto : {{ tiendas.telefonoContacto }}</h5>
            </div>
            {% endfor %}
        </div>
    </body>
</html>